steps:
- name: build and push to registries
  image: docker.io/woodpeckerci/plugin-docker-buildx
  settings:
    repo:
    - ghcr.io/nightly_brew/dockerproxy
    - gitea.moonlit-room.org/nightly_brew/dockerproxy
    platform: linux/amd64
    tag: latest
    logins:
    - registry: https://ghcr.io
      username:
        from_secret: github_registry_username
      password:
        from_secret: github_registry_password
    - registry: https://gitea.moonlit-room.org
      username:
        from_secret: gitea_registry_username
      password:
        from_secret: gitea_registry_password