when:
- event: "push"
  branch: "main"
- path:
    exclude: ['README.md', 'renovate.json', 'examples/**']

steps:
- name: build and push to registries
  image: docker.io/woodpeckerci/plugin-docker-buildx
  settings:
    repo:
    - gitea.moonlit-room.org/nightly_brew/dockerproxy
    - ghcr.io/nightly-brew/dockerproxy
    platform: linux/amd64
    tag: latest
    logins:
    - registry: https://gitea.moonlit-room.org
      username:
        from_secret: gitea_registry_username
      password:
        from_secret: gitea_registry_password
    - registry: https://ghcr.io
      username:
        from_secret: github_registry_username
      password:
        from_secret: github_registry_password